### ISSUE TITLE
Environment Variables

### ISSUE THREAD

**Issue by nickwinger** [BenMorris/FunctionsCustomSercuity#10]
Hello and thank you for the Sample Code.
I read through the Tutorial but i don't what these Environment Variables are:
IssuerToken, Audience and Issuer.

I mean i tried to get the Audience and Issure from the OpenID-Token i receive from AzureAuthentication, but what or where is this IssuerToken ???

Thanks,
Nick

**Comment by BenMorris** [comment]
These are values provided by the token issuer that are used to decrypt and validate the JWT token.

- The "issuerToken" is the signing key used to decrypt the token
- The "audience" and "issuer" are compared against claims in the JWT token to check it is valid.

This should be explained in the original blog post (see "Validating the token"): https://www.ben-morris.com/custom-token-authentication-in-azure-functions-using-bindings/
