### ISSUE TITLE
What are the values do you have in App Config

### ISSUE THREAD

**Issue by gethari** [BenMorris/FunctionsCustomSercuity#2]
Can you please explain the below code ?
![image](https://user-images.githubusercontent.com/20477956/55304360-badeb400-5468-11e9-850d-4b26f87096c1.png)

**Comment by BenMorris** [comment]
You'll need a file called local.settings.json sitting in your application root that defines these values. The values themselves are provided by your token issuer. The file will look something like this:
```
{
    "IsEncrypted": false,
    "Values": {
        "Issuer": "[token issuer url]",
        "IssuerToken": "[issuer token]",
        "Audience": "[token issuer audience]",
    }
}
```
