### ISSUE TITLE
Update documentation with new IFunctionsHostBuilder on Configure method from Startup.

### ISSUE THREAD

**Issue by germancasares** [BenMorris/FunctionsCustomSercuity#6]
Now that Azure functions have dependency injection built-in, as per https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection.

What should we do instead of :

```csharp
[assembly: WebJobsStartup(typeof(Startup))]
namespace FunctionsCustomSercuity
{
    /// <summary>
    /// Runs when the Azure Functions host starts.
    /// </summary>
    public class Startup : IWebJobsStartup
    {
        public void Configure(IWebJobsBuilder builder)
        {
            builder.AddAccessTokenBinding();
        }
    }
}
```

**Comment by BenMorris** [comment]
The solution will look a lot more like this branch:

https://github.com/BenMorris/FunctionsCustomSercuity/tree/NativeInjectionSupport

The only downside of using the new native DI is that you have to remember to call a validation method on every function. Probably not too great a burden.

I'll update all the main code (and related blog post) soon.

**Comment by BenMorris** [comment]
The main branch and blog post have been updated with both approaches. That said, dependency injection involves much less code so is the approach I would recommend.
